<?php
	namespace app\index\controller;
	use \think\Controller;
	use \think\Url;
	class UserInfo extends Controller{
		protected $beforeActionList = [
			'one',
			'two'=>['only'=>'index'],//仅让方法index使用,
			'three'=>['except'=>'index'],//不让方法index使用
		];#前置方法
		public function _initialize()
		{
			parent::_initialize(); // TODO: Change the autogenerated stub
			echo '初始化调用';
			echo '<hr>';
		}
		
		public function index(){
			return 'UserInfo index page';
		}
		public function one(){
			echo "one<hr>";
		}
		public function two(){
			echo "two<hr>";
		}
		public function three(){
			echo "three<hr>";
		}
		public function go(){
			//$this->success('成功',url('index/index/test1'));
			//$this->redirect(url('index/index/test1'),301);
			$this->redirect('index/index/test',['name'=>'mxw','id'=>'1'],302);
		}
	}
?>